config/routes.rb
IlYanzhao::Application.routes.draw do

  resources :imported_customers

  resources :customer_level_configs

  resources :journals do
    get :search,:on => :collection
  end

  resources :remittances do
    get :search,:on => :collection
  end

  resources :send_list_backs do
    get :search,:on => :collection
  end

  resources :send_list_posts do
    get :search,:on => :collection
  end

  resources :send_lists do
    get :search,:on => :collection
  end

  resources :senders

  resources :goods_exceptions do
    get :show_authorize,:on => :member
    get :show_claim,:on => :member
    get :show_identify,:on => :member
    get :search,:on => :collection
  end

  resources :short_fee_infos

  resources :il_configs

  resources :config_cashes

  resources :config_transits

  resources :roles

  devise_for :users,:controllers => {:sessions => "sessions"} do
    get "users/new_session_default",:to => "sessions#new_session_default",:as => :user_root
    put  "users/update_session_default",:to => "sessions#update_session_default",:as => :update_session_default
  end

  resources :users do
    get :edit_password,:on => :collection
    get :reset_usb_pin,:on => :member
    put :update_password,:on => :collection
  end

  resources :transit_deliver_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :transit_companies

  resources :transit_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :post_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :cash_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    get :process_handle,:on => :member
    resources :carrying_bills
  end

  resources :cash_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :vips do
    get :search,:on => :collection
  end

  resources :customers

  resources :banks

  resources :refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end
  resources :receive_refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :settlements do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :deliver_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :distribution_lists do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :arrive_load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :hand_transit_bills do
    get :search,:on => :collection
  end

  resources :transit_bills do
    get :search,:on => :collection
  end

  resources :hand_bills do
    get :search,:on => :collection
  end

  resources :return_bills do
    get :before_new,:on => :collection
    get :search,:on => :collection
  end

  resources :orgs
  resources :branches
  resources :departments

  resources :carrying_bills do
    get :rpt_turnover,:on => :collection
    get :turnover_chart,:on => :collection
    get :search,:on => :collection
    get :simple_search,:on => :collection
    put :reset,:on => :member
  end

  resources :computer_bills do
    get :search,:on => :collection
  end

  root :to => "dashboard#index"

end

app/models/settlement.rb
#coding: utf-8
class Settlement < ActiveRecord::Base
  belongs_to :user
  has_many :carrying_bills
  belongs_to :org
  validates_presence_of :org_id
  #定义状态机
  state_machine :initial => :billed do
    after_transition do |settlement,transition|
      settlement.carrying_bills.each {|bill| bill.standard_process}
    end
    event :process do
      transition :billed =>:settlemented
    end
  end

  default_value_for :bill_date,Date.today
  #结算员
  def user_name
    self.user.try(:username)
  end

  #组织机构
  def org_name
    self.org.name
  end
  #合计
  def sum_fee
    self.sum_carrying_fee + self.sum_goods_fee - self.sum_transit_carrying_fee - self.sum_transit_hand_fee
  end
  #导出到csv
  def to_csv
    ret = ["结算员:",self.user_name,"结算单位:",self.org_name,"结算日期:",self.bill_date].export_line_csv(true)
    ret = ret + ["提付运费:",self.sum_carrying_fee,"代收货款:",self.sum_goods_fee,"合计:",self.sum_fee].export_line_csv
    csv_carrying_bills = CarryingBill.to_csv(self.carrying_bills.search,Settlement.carrying_bill_export_options,false)
    ret + csv_carrying_bills
  end
  private
  def self.carrying_bill_export_options
    {
        :only => [],
        :methods => [
          :bill_date,:bill_no,:goods_no,:from_customer_name,:from_customer_phone,:from_customer_mobile,
          :to_customer_name,:to_customer_phone,:to_customer_mobile,
          :pay_type_des,
          :carrying_fee_th,:goods_fee,:insured_fee,
          :note,:human_state_name
      ]}
  end

end

app/controllers/settlements_controller.rb
#coding: utf-8
class SettlementsController < BaseController
  table :org,:bill_date,:sum_goods_fee,:sum_carrying_fee,:user,:human_state_name,:note
  include BillOperate
  def new
    @settlement = Settlement.new
    @settlement = Settlement.new_with_org_id if params[:settlement].present?
  end
  #GET search
  #显示查询窗口
  def search
    render :partial => "search"
  end
  def show
    super do |format|
      format.csv {send_data resource.to_csv}
    end
  end

end

app/helpers/settlements_helper.rb
#coding: utf-8
#coding: utf-8
module SettlementsHelper
end

app/views/settlements/_extra_toolbar.html.erb
<%if params[:action] == "show"%>
  <li>
    <%= link_to image_tag("document-excel-table.png",:alt => "导出为EXCEL"), resource_path(resource,:format => :csv),:title => "导出为EXCEL",:class => "tipsy"  %>
  </li>
<%end%>

app/views/settlements/_form.html.erb
<%= semantic_form_for resource, :remote => true,:html =>{:id => "settlement_form"}  do |f|%>
  <%=f.error_messages %>
  <%= f.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
  <table class='table'>
    <tr>
      <td>结算员:</td>
      <td><%=current_user%></td>
      <td>结算单位:</td>
      <td>
        <%=f.select :org_id,current_ability_orgs_for_select,{},{:class => "select_org",:id => "to_org_id"} %>
      </td>
      <td>结算日期:<%=Date.today().strftime('%Y-%m-%d')%></td>
    </tr>
    <tr>
      <td>返程货款:<%=f.text_field :sum_goods_fee ,:readonly => true,:size => 10 %></td>
      <td>提货付运费:<%=f.text_field :sum_carrying_fee ,:readonly => true,:size => 10 %></td>
      <td>中转运费:<%=f.text_field :sum_transit_carrying_fee ,:readonly => true,:size => 10 %></td>
      <td>中转手续费:<%=f.text_field :sum_transit_hand_fee ,:readonly => true,:size => 10 %></td>
      <td>合计:<span id='settlement_sum_fee'><%=resource.sum_fee %></span></td>
    </tr>
    <tr>
      <td>备注</td>
      <td colspan='4'>
        <%=f.text_field :note %>
      </td>
    </tr>
  </table>
<% end%>

app/views/settlements/_form_after.html.erb
<div class='actions-bar text-right'>
  <%= link_to image_tag("plus-white.png") + "生成结算清单",carrying_bills_path,:remote => true,:id=>"btn_generate_settlement", :class => 'tipsy sexybutton sexysimple sexyblue',:title => "生成结算清单" %>
</div>
<hr/>
<div id="table_wrap">
</div>

app/views/settlements/_search.html.erb
<%= semantic_form_for resource_class.search,:html => {:method => :get,:style => "width : 300px;" } do |f|%>
  <%= hidden_field_tag :direction,params[:direction] %>
  <%= hidden_field_tag :sort,params[:sort] %>
  <%= f.inputs do %>
    <%= f.input :org_id_eq,:label => "分理处/分公司",:as => :select,:collection => current_ability_orgs_for_select,:input_html => {:class => "select_org",:title => "可录入拼音简写查询发货地"} %>
    <%= f.input :bill_date_gte,:label => "结算日期",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
    <%= f.input :bill_date_lte,:label => "~",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
  <% end %>
  <%=f.buttons do %>
    <%=submit_tag "查询结算员交款清单",:class => "sexybutton sexysimple sexyblue" %>
  <% end %>
<% end%>

app/views/settlements/_show.html.erb
<table class='table' data-detailUrl='<%=settlement_carrying_bills_path(resource)%>' data-params='{"hide_fields": ".carrying_fee,.insured_fee","show_fields": ".carrying_fee_th,.th_amount"}'>
  <tr>
    <td>结算员:</td>
    <td><%=resource.user%></td>
    <td>结算单位:</td>
    <td>
      <%=resource.org.name %>
    </td>
    <td>结算日期:</td>
    <td> <%=resource.created_at.strftime('%Y-%m-%d')%></td>
    <td colspan='4'>&nbsp;</td>
  </tr>
  <tr>
    <td>返程货款:</td>
    <td><%=resource.sum_goods_fee %></td>
    <td>提货付运费:</td>
    <td><%=resource.sum_carrying_fee%></td>
    <td>中转运费:</td>
    <td><%=resource.sum_transit_carrying_fee%></td>
    <td>中转手续费:</td>
    <td><%=resource.sum_transit_hand_fee%></td>
    <td>合计:</td>
    <td><%=resource.sum_fee %></td>
  </tr>
  <tr>
    <td>备注</td>
    <td colspan='9'>
      <%=resource.note %>
    </td>
  </tr>
</table>
<div id="table_wrap"></div>

app/views/settlements/_table.html.erb
<table id="<%= resource_class.name.underscore.pluralize %>_index_table" class="table">
  <tr>
    <th><%=check_box_tag "check_all",1,false,:title => "选择/不选全部",:class => "tipsy" %></th>
      <th>序号</th>
      <th>结算日期</th>
      <th>结算机构</th>
      <th>结算员</th>
      <th>返程运费</th>
      <th>代收货款</th>
      <th>合计</th>
  </tr>
  <% collection.each_with_index do |resource,index| %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td><%=check_box_tag "selector_#{resource.id}",resource.id %></td>
      <td><%= order_no(index,params[:page]) %></td>
      <td><%= resource.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= resource.org.name %></td>
      <td>&nbsp;</td>
      <td><%= resource.sum_goods_fee %></td>
      <td><%= resource.sum_carrying_fee %></td>
      <td><%= resource.sum_fee %></td>
    </tr>
  <% end %>
</table>

app/views/settlements/_table_with_select.html.erb
<table id="<%= resource_class.name.underscore.pluralize %>_index_table" class="table">
  <tr>
    <th><%=check_box_tag "check_all",1,false,:title => "选择/不选全部",:class => "tipsy" %></th>
      <th>序号</th>
      <th>结算日期</th>
      <th>结算机构</th>
      <th>结算员</th>
      <th>返程运费</th>
      <th>代收货款</th>
      <th>中转运费</th>
      <th>中转手续费</th>
      <th>合计</th>
  </tr>
  <% collection.each_with_index do |resource,index| %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td><%=check_box_tag "selector_#{resource.id}",resource.id %></td>
      <td><%= order_no(index,params[:page]) %></td>
      <td><%= resource.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= resource.org.name %></td>
      <td><%= resource.user%></td>
      <td><%= resource.sum_goods_fee %></td>
      <td><%= resource.sum_carrying_fee %></td>
      <td><%= resource.sum_transit_carrying_fee %></td>
      <td><%= resource.sum_transit_hand_fee %></td>
      <td><%= resource.sum_fee %></td>
    </tr>
  <% end %>
</table>

app/views/settlements/index.js.erb
$('#table_wrap').html('<%= escape_javascript(render("table_with_select")) %>');