config/routes.rb
IlYanzhao::Application.routes.draw do

  resources :imported_customers

  resources :customer_level_configs

  resources :journals do
    get :search,:on => :collection
  end

  resources :remittances do
    get :search,:on => :collection
  end

  resources :send_list_backs do
    get :search,:on => :collection
  end

  resources :send_list_posts do
    get :search,:on => :collection
  end

  resources :send_lists do
    get :search,:on => :collection
  end

  resources :senders

  resources :goods_exceptions do
    get :show_authorize,:on => :member
    get :show_claim,:on => :member
    get :show_identify,:on => :member
    get :search,:on => :collection
  end

  resources :short_fee_infos

  resources :il_configs

  resources :config_cashes

  resources :config_transits

  resources :roles

  devise_for :users,:controllers => {:sessions => "sessions"} do
    get "users/new_session_default",:to => "sessions#new_session_default",:as => :user_root
    put  "users/update_session_default",:to => "sessions#update_session_default",:as => :update_session_default
  end

  resources :users do
    get :edit_password,:on => :collection
    get :reset_usb_pin,:on => :member
    put :update_password,:on => :collection
  end

  resources :transit_deliver_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :transit_companies

  resources :transit_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :post_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :cash_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    get :process_handle,:on => :member
    resources :carrying_bills
  end

  resources :cash_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :vips do
    get :search,:on => :collection
  end

  resources :customers

  resources :banks

  resources :refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end
  resources :receive_refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :settlements do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :deliver_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :distribution_lists do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :arrive_load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :hand_transit_bills do
    get :search,:on => :collection
  end

  resources :transit_bills do
    get :search,:on => :collection
  end

  resources :hand_bills do
    get :search,:on => :collection
  end

  resources :return_bills do
    get :before_new,:on => :collection
    get :search,:on => :collection
  end

  resources :orgs
  resources :branches
  resources :departments

  resources :carrying_bills do
    get :rpt_turnover,:on => :collection
    get :turnover_chart,:on => :collection
    get :search,:on => :collection
    get :simple_search,:on => :collection
    put :reset,:on => :member
  end

  resources :computer_bills do
    get :search,:on => :collection
  end

  root :to => "dashboard#index"

end

app/models/goods_exception.rb
#coding: utf-8
class GoodsException < ActiveRecord::Base
  belongs_to :carrying_bill
  belongs_to :user
  belongs_to :org
  #授权核销信息
  has_one :gexception_authorize_info
  #理赔信息
  has_one :claim
  #责任鉴定信息
  has_one :goods_exception_identify
  accepts_nested_attributes_for :gexception_authorize_info,:claim,:goods_exception_identify

  validates_presence_of :org_id
  #定义状态机
  state_machine :initial => :submited do
    event :process do
      #已上报 -- 已授权核销 --- 已赔偿 -- 责任已鉴定
      transition :submited =>:authorized,:authorized => :compensated,:compensated => :identified
    end
  end

  #FIXME 缺省值设定应定义到state_machine之后
  default_value_for :bill_date,Date.today

  EXCEPT_LACK= "LA"           #少货
  EXCEPT_SHORTAGE = "SH"      #短缺
  EXCEPT_DAMAGED = "DA"       #破损
  #付款方式描述
  def self.exception_types
    {
      "少货" => EXCEPT_LACK,          #少货
      "丢缺" => EXCEPT_SHORTAGE,      #短缺
      "破损" => EXCEPT_DAMAGED        #破损
    }
  end
  def except_des
      except_des = ""
      GoodsException.exception_types.each {|des,code| except_des = des if code == self.exception_type }
      except_des
  end

end

app/controllers/goods_exceptions_controller.rb
#coding: utf-8
class GoodsExceptionsController < BaseController
  table :bill_date,:org,:carrying_bill,:except_des,:except_num,:human_state_name,:note,:user
  #需要跳过对update的权限检查,在进行核销/理赔/责任鉴定时候,使用了update
  skip_authorize_resource :only => :update
  def create
    bill = resource_class.new(params[resource_class.model_name.underscore])
    get_resource_ivar || set_resource_ivar(bill)
    bill.carrying_bill_id  = params[:bill_ids].first  unless params[:bill_ids].blank?
    create!
  end
  def update
    bill = resource_class.find(params[:id])
    get_resource_ivar || set_resource_ivar(bill)
    bill.process
    update!
  end

  #GET /goods_exceptions/1/show_authorize
  #显示授权核销界面
  def show_authorize
    goods_exception = resource_class.find(params[:id])
    get_resource_ivar || set_resource_ivar(goods_exception)
    goods_exception.build_gexception_authorize_info
  end
  #GET /goods_exceptions/1/show_claim
  #显示理赔界面
  def show_claim
    goods_exception = resource_class.find(params[:id])
    get_resource_ivar || set_resource_ivar(goods_exception)
    goods_exception.build_claim
  end
  #GET /goods_exceptions/1/show_identify
  #显示责任鉴定界面
  def show_identify
    goods_exception = resource_class.find(params[:id])
    get_resource_ivar || set_resource_ivar(goods_exception)
    goods_exception.build_goods_exception_identify
  end
  #显示查询窗口
  def search
    render :partial => "search"
  end

end

app/helpers/goods_exceptions_helper.rb
#coding: utf-8
#coding: utf-8
module GoodsExceptionsHelper
  #货物异常类别方式显示
  def exception_type_des(exception_type)
    exception_type_des = ""
    GoodsException.exception_types.each {|des,code| exception_type_des = des if code == exception_type }
    exception_type_des
  end
  #核销方式
  def exception_op_type_des(op_type)
    op_type_des = ""
    GexceptionAuthorizeInfo.op_types.each {|des,code| op_type_des = des if code == op_type }
    op_type_des
  end
  def goods_exception_states_for_select
    GoodsException.state_machine.states.collect{|state| [state.human_name,state.value] }
  end
end

app/views/goods_exceptions/_dynamic_toolbar.html.erb
<!--动态toolbar-->
<div class="secondary-navigation">
  <ul class="wat-cf">
    <%if can? :read,resource_class%>
      <li class="first">
        <%= link_to image_tag("grid.png",:alt => "#{resource_class.model_name.human}列表") , collection_path,:title => "#{resource_class.model_name.human}列表",:class => "tipsy"  %>
      </li>
      <%if self.respond_to?("search_#{controller_name.tableize}_path")%>
        <li><%= link_to image_tag("application-search-result.png",:alt => "查询#{resource_class.model_name.human}"),self.send("search_#{controller_name.tableize}_path"),:title => "查询#{resource_class.model_name.human}",:class => "fancybox tipsy" %></li>
      <%end%>
    <%end%>
    <%if can? :create,resource_class%>
      <li>
        <%= link_to image_tag("application--plus.png",:alt => "新建#{resource_class.model_name.human}"), new_resource_path,:title => "新建#{resource_class.model_name.human}",:class => "tipsy"  %>
      </li>
    <%end%>

    <%if params[:action] == "new"%>
      <li>
        <%= link_to_function image_tag("disk-black.png",:alt => "保存#{resource_class.model_name.human}"), "$('##{resource_class.model_name.underscore}_form').trigger('submit')",:title => "保存#{resource_class.model_name.human}",:class => "tipsy"  %>
      </li>
    <%end%>
    <%if ["edit","show_authorize","show_claim","show_identify"].include? params[:action] %>
      <li>
        <%= link_to_function image_tag("disk-black.png",:alt => "保存#{resource_class.model_name.human}"), "$('##{resource_class.model_name.underscore}_form').unbind('ajax:before').trigger('submit')",:title => "保存#{resource_class.model_name.human}",:class => "tipsy"  %>
      </li>
    <%end%>
    <%if params[:action] == "show"%>
      <%if can? :show_authorize,resource and resource.submited?%>
        <li>
          <%= link_to image_tag("balance--pencil.png",:alt => "核销理赔记录"),  show_authorize_goods_exception_path(resource),:title => "核销理赔记录",:class => "tipsy" %>
        </li>
      <%end%>
      <%if can? :show_claim,resource and resource.authorized?%>
        <li>
          <%= link_to image_tag("money-coin.png",:alt => "录入理赔信息"),  show_claim_goods_exception_path(resource),:title => "录入理赔信息",:class => "tipsy" %>
        </li>
      <%end%>
      <%if can? :show_identify,resource and resource.compensated?%>
        <li>
          <%= link_to image_tag("document-stamp.png",:alt => "责任鉴定"),  show_identify_goods_exception_path(resource),:title => "责任鉴定",:class => "tipsy" %>
        </li>
      <%end%>
    <%end%>
  </ul>
</div>   

app/views/goods_exceptions/_form.html.erb
<%= render "form_before" %>
<%= semantic_form_for resource ,:remote => true,:html => {:id => "goods_exception_form"} do |f|%>
  <%=f.error_messages %>
  <%= f.inputs "异常信息" do%>
    <%= f.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
    <%= f.input :bill_date,:as => :string,:input_html =>{:readonly => true,:size => 20,:class => 'datepicker'} %>
    <%= f.input :org_id ,:as => :select,:collection => current_ability_orgs_for_select,:include_blank => false,:input_html => {:class => "select_org"} %>
    <%= f.input :exception_type ,:as => :select,:collection => GoodsException.exception_types,:include_blank => false %>
    <%= f.input :except_num %>
    <%= f.input :note ,:as => :string,:input_html => {:size => 100} %>
  <%end%>
<% end%>

app/views/goods_exceptions/_form_before.html.erb
<div class='actions-bar'>
  <input type='text' size="10" class="search_box" data-params = '{"search[state_in][]" : ["billed","loaded","shipped","reached","distributed"],"search[type_in][]" : ["ComputerBill","HandBill","TransitBill","HandTransitBill"],"show_multi" : ""}'/>
</div>
<div id="table_wrap"></div>

app/views/goods_exceptions/_form_with_authorize_info.html.erb
<%= semantic_form_for resource ,:remote => true,:html => {:id => "goods_exception_form"} do |f|%>
  <%=f.error_messages %>
  <%=f.semantic_fields_for :gexception_authorize_info do |a_info|%>
    <%= a_info.inputs "授权核销信息" do%>
      <%= a_info.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
      <%= a_info.input :op_type,:as => :select,:collection => GexceptionAuthorizeInfo.op_types,:include_blank => false %>
      <%= a_info.input :compensation_fee %>
      <%= a_info.input :note ,:as => :string,:input_html => {:size => 100} %>
    <%end%>
  <%end%>
<% end%>

app/views/goods_exceptions/_form_with_claim.html.erb
<%= semantic_form_for resource ,:remote => true,:html => {:id => "goods_exception_form"} do |f|%>
  <%=f.error_messages %>
  <%=f.semantic_fields_for :claim do |claim|%>
    <%= claim.inputs "理赔信息" do%>
      <%= claim.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
      <%= claim.input :bill_date,:as => :string,:input_html => {:size => 10,:readonly => true,:class => 'datepicker'} %>
      <%= claim.input :act_compensate_fee %>
      <%= claim.input :note ,:as => :string,:input_html => {:size => 100} %>
    <%end%>
  <%end%>
<% end%>

app/views/goods_exceptions/_form_with_identify.html.erb
<%= semantic_form_for resource ,:remote => true,:html => {:id => "goods_exception_form"} do |f|%>
  <%=f.error_messages %>
  <%=f.semantic_fields_for :goods_exception_identify do |identify|%>
    <%= identify.inputs "责任鉴定" do%>
      <%= identify.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
      <%= identify.input :bill_date,:as => :string,:input_html => {:size => 10,:readonly => true,:class => 'datepicker'} %>
      <%= identify.input :from_org_fee %>
      <%= identify.input :to_org_fee %>
      <%= identify.input :note ,:as => :string,:input_html => {:size => 100} %>
    <%end%>
  <%end%>
<% end%>

app/views/goods_exceptions/_search.html.erb
<%= semantic_form_for resource_class.search,:html => {:method => :get,:style => "width : 300px;" } do |f|%>
  <%= hidden_field_tag :direction,params[:direction] %>
  <%= hidden_field_tag :sort,params[:sort] %>
  <%= f.inputs do %>
    <%= f.input :carrying_bill_bill_no_eq,:label =>"运单号",:input_html => {:size => 30} %>
    <%= f.input :bill_date_gte,:label => "上报日期",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
    <%= f.input :bill_date_lte,:label => "~",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
    <%= f.input :org_id_eq,:label =>"组织机构",:as => :select,:collection => current_ability_orgs_for_select,:include_blank => true,:input_html => {:class => "select_org",:title => "可录入拼音简写查询到货地(例如:安阳,可录入ay)"} %>

    <%= f.input :state_eq,:label => "状态",:as => :select,:collection => goods_exception_states_for_select,:include_blank => true %>
  <% end %>
  <%=f.buttons do %>
    <%=submit_tag "查询理赔信息",:class => "sexybutton sexysimple sexyblue" %>
  <% end %>
<% end%>

app/views/goods_exceptions/_show.html.erb
<table class='table'>
  <tr>
    <td>上报机构</td>
    <td><%=resource.org.name%></td>
    <td>上报日期</td>
    <td><%=resource.bill_date.strftime("%Y-%m-%d")%></td>
    <td>上报人</td>
    <td><%=resource.user%></td>
  </tr>
  <tr>
    <td>异常类型</td>
    <td><%=exception_type_des(resource.exception_type) %></td>
    <td>异常数量</td>
    <td><%=resource.except_num%></td>
    <td>运单号/货号</td>
    <td>
      <%=link_to "#{resource.carrying_bill.bill_no}/#{resource.carrying_bill.goods_no}",polymorphic_path(resource.carrying_bill,:format => :js),:class => 'fancybox'%>
    </td>
  </tr>
  <tr>
    <td>备注</td>
    <td colspan='3'><%=resource.note%></td>
    <td>状态</td>
    <td><%=resource.human_state_name%></td>
  </tr>
  <%if resource.gexception_authorize_info.present?%>
    <tr>
      <td>核销时间</td>
      <td><%=resource.gexception_authorize_info.bill_date.strftime("%Y-%m-%d")%></td>
      <td>赔偿方式</td>
      <td><%=exception_op_type_des(resource.gexception_authorize_info.op_type) %></td>
      <td>拟赔金额</td>
      <td><%=resource.gexception_authorize_info.compensation_fee %></td>
    </tr>
    <tr>
      <td>备注</td>
      <td colspan='3'><%=resource.gexception_authorize_info.note %></td>
      <td>核销人</td>
      <td><%=resource.gexception_authorize_info.user%></td>
    </tr>
  <%end%>
  <%if resource.claim.present?%>
    <tr>
      <td>理赔时间</td>
      <td><%=resource.claim.bill_date.strftime("%Y-%m-%d")%></td>
      <td>实赔金额</td>
      <td><%=resource.claim.act_compensate_fee %></td>
      <td>理赔人</td>
      <td><%=resource.claim.user %></td>
    </tr>
    <tr>
      <td>备注</td>
      <td colspan='5'><%=resource.claim.note %></td>
    </tr>
  <%end%>
  <%if resource.goods_exception_identify.present?%>
    <tr>
      <td>鉴定时间</td>
      <td><%=resource.goods_exception_identify.bill_date.strftime("%Y-%m-%d")%></td>
      <td>发货地赔付</td>
      <td><%=resource.goods_exception_identify.from_org_fee %></td>
      <td>到货地赔付</td>
      <td><%=resource.goods_exception_identify.to_org_fee %></td>
    </tr>
    <tr>
      <td>备注</td>
      <td colspan='3'><%=resource.goods_exception_identify.note %></td>
      <td>鉴定人</td>
      <td><%=resource.goods_exception_identify.user %></td>
    </tr>
  <%end%>

</table>

app/views/goods_exceptions/show_authorize.html.erb
<div class="block">
  <%= render "dynamic_toolbar" %>
  <div class="content">            
    <h2 class="title">货物异常情况核销</h2>
    <div class="inner">
      <%= render "show" %>
      <div id='<%="#{resource_class.name.underscore}_form_wrap" %>' >
        <%= render 'form_with_authorize_info' %>
      </div>
    </div>
  </div>
  <%= render "dynamic_toolbar" %>
</div>

app/views/goods_exceptions/show_claim.html.erb
<div class="block">
  <%= render "dynamic_toolbar" %>
  <div class="content">            
    <h2 class="title">理赔信息录入</h2>
    <div class="inner">
      <%= render "show" %>
      <div id='<%="#{resource_class.name.underscore}_form_wrap" %>' >
        <%= render 'form_with_claim' %>
      </div>
    </div>
  </div>
  <%= render "dynamic_toolbar" %>
</div>

app/views/goods_exceptions/show_identify.html.erb
<div class="block">
  <%= render "dynamic_toolbar" %>
  <div class="content">            
    <h2 class="title">责任鉴定</h2>
    <div class="inner">
      <%= render "show" %>
      <div id='<%="#{resource_class.name.underscore}_form_wrap" %>' >
        <%= render 'form_with_identify' %>
      </div>
    </div>
  </div>
  <%= render "dynamic_toolbar" %>
</div>