config/routes.rb
IlYanzhao::Application.routes.draw do

  resources :imported_customers

  resources :customer_level_configs

  resources :journals do
    get :search,:on => :collection
  end

  resources :remittances do
    get :search,:on => :collection
  end

  resources :send_list_backs do
    get :search,:on => :collection
  end

  resources :send_list_posts do
    get :search,:on => :collection
  end

  resources :send_lists do
    get :search,:on => :collection
  end

  resources :senders

  resources :goods_exceptions do
    get :show_authorize,:on => :member
    get :show_claim,:on => :member
    get :show_identify,:on => :member
    get :search,:on => :collection
  end

  resources :short_fee_infos

  resources :il_configs

  resources :config_cashes

  resources :config_transits

  resources :roles

  devise_for :users,:controllers => {:sessions => "sessions"} do
    get "users/new_session_default",:to => "sessions#new_session_default",:as => :user_root
    put  "users/update_session_default",:to => "sessions#update_session_default",:as => :update_session_default
  end

  resources :users do
    get :edit_password,:on => :collection
    get :reset_usb_pin,:on => :member
    put :update_password,:on => :collection
  end

  resources :transit_deliver_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :transit_companies

  resources :transit_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :post_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :cash_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    get :process_handle,:on => :member
    resources :carrying_bills
  end

  resources :cash_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :vips do
    get :search,:on => :collection
  end

  resources :customers

  resources :banks

  resources :refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end
  resources :receive_refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :settlements do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :deliver_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :distribution_lists do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :arrive_load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :hand_transit_bills do
    get :search,:on => :collection
  end

  resources :transit_bills do
    get :search,:on => :collection
  end

  resources :hand_bills do
    get :search,:on => :collection
  end

  resources :return_bills do
    get :before_new,:on => :collection
    get :search,:on => :collection
  end

  resources :orgs
  resources :branches
  resources :departments

  resources :carrying_bills do
    get :rpt_turnover,:on => :collection
    get :turnover_chart,:on => :collection
    get :search,:on => :collection
    get :simple_search,:on => :collection
    put :reset,:on => :member
  end

  resources :computer_bills do
    get :search,:on => :collection
  end

  root :to => "dashboard#index"

end

app/models/transfer_pay_info.rb
#coding: utf-8
#转账提款信息
class TransferPayInfo < PayInfo
end

app/controllers/transfer_pay_infos_controller.rb
#coding: utf-8
class TransferPayInfosController < BaseController
  table :bill_date,:customer_name,:bill_no,:from_customer,:sum_goods_fee,:sum_k_carrying_fee,:sum_k_hand_fee,:sum_act_pay_fee
  include BillOperate
  #GET search
  #显示查询窗口
  def search
    @search = resource_class.search(params[:search])
    render :partial => "shared/pay_infos/search",:object => @search
  end
  def index
    super do |format|
      format.csv {send_data resource_class.to_csv(@search)}
    end
  end
end

app/helpers/transfer_pay_infos_helper.rb
#coding: utf-8
#coding: utf-8
module TransferPayInfosHelper
end

app/views/transfer_pay_infos/_extra_toolbar.html.erb
<%= render "shared/pay_infos/extra_toolbar" %>

app/views/transfer_pay_infos/_form.html.erb
<%=render "shared/pay_infos/form"%>

app/views/transfer_pay_infos/_form_after.html.erb
<hr />
<%if params[:show_multi].present?%>
  <div class='actions-bar text-right wat-cf'>
    <div class='float-left'>
      <%=form_for TransferPaymentList.search,:remote => true do |f|%>
        <%=f.label :bill_date_gte,"查询转账支付清单:",:readonly => true,:class => "datepicker"%>
        <%=f.text_field :bill_date_gte,:value => Date.today,:readonly => true,:class => "datepicker",:size => 10%>
        <%=f.label :bill_date_lte,"~"%>
        <%=f.text_field :bill_date_lte,:value => Date.today,:readonly => true,:class => "datepicker",:size => 10%>
        <%=f.hidden_field :carrying_bills_from_customer_id_is_not_null,:value => "1"%>
        <%=f.hidden_field :carrying_bills_state_eq,:value => "payment_listed"%>
        <%=f.hidden_field :state_eq,:value => "transfered"%>
        <%=image_submit_tag "arrow-circle-double-135.png",:class => "tipsy",:title => "查询还有未提款的代收货款转账支付清单" %>
      <%end%>
    </div>
    <%= link_to image_tag("plus-white.png") + "生成批量提款清单", carrying_bills_path,:remote => true,:class => 'tipsy sexybutton sexysimple sexyblue',:title => "生成批量提款清单",:id => 'btn_generate_transfer_pay_info' %>
  </div>
<%else%>
  <%= render "shared/pay_infos/form_before" %>
<%end%>
<hr />
<div id="table_wrap"></div>

app/views/transfer_pay_infos/_show.html.erb
<%= render "shared/pay_infos/show" %>
<div id="table_wrap" data-detailUrl='<%=transfer_pay_info_carrying_bills_path(resource)%>' data-params='{"hide_fields" : ".carrying_fee,.insured_fee","show_fields" : ".k_carrying_fee,.k_hand_fee,.act_pay_fee"}'></div>

app/views/transfer_pay_infos/_table.html.erb
<%= render "shared/pay_infos/table" %>