config/routes.rb
IlYanzhao::Application.routes.draw do

  resources :imported_customers

  resources :customer_level_configs

  resources :journals do
    get :search,:on => :collection
  end

  resources :remittances do
    get :search,:on => :collection
  end

  resources :send_list_backs do
    get :search,:on => :collection
  end

  resources :send_list_posts do
    get :search,:on => :collection
  end

  resources :send_lists do
    get :search,:on => :collection
  end

  resources :senders

  resources :goods_exceptions do
    get :show_authorize,:on => :member
    get :show_claim,:on => :member
    get :show_identify,:on => :member
    get :search,:on => :collection
  end

  resources :short_fee_infos

  resources :il_configs

  resources :config_cashes

  resources :config_transits

  resources :roles

  devise_for :users,:controllers => {:sessions => "sessions"} do
    get "users/new_session_default",:to => "sessions#new_session_default",:as => :user_root
    put  "users/update_session_default",:to => "sessions#update_session_default",:as => :update_session_default
  end

  resources :users do
    get :edit_password,:on => :collection
    get :reset_usb_pin,:on => :member
    put :update_password,:on => :collection
  end

  resources :transit_deliver_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :transit_companies

  resources :transit_infos do
    get :search,:on => :collection
    resource :carrying_bill
  end

  resources :post_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :cash_pay_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :transfer_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    get :process_handle,:on => :member
    resources :carrying_bills
  end

  resources :cash_payment_lists do
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :vips do
    get :search,:on => :collection
  end

  resources :customers

  resources :banks

  resources :refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end
  resources :receive_refounds do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :settlements do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :deliver_infos do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :distribution_lists do
    get :search,:on => :collection
    resources :carrying_bills
  end

  resources :load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :arrive_load_lists do
    get :process_handle,:on => :member
    get :search,:on => :collection
    get :export_excel,:on => :member
    resources :carrying_bills
  end

  resources :hand_transit_bills do
    get :search,:on => :collection
  end

  resources :transit_bills do
    get :search,:on => :collection
  end

  resources :hand_bills do
    get :search,:on => :collection
  end

  resources :return_bills do
    get :before_new,:on => :collection
    get :search,:on => :collection
  end

  resources :orgs
  resources :branches
  resources :departments

  resources :carrying_bills do
    get :rpt_turnover,:on => :collection
    get :turnover_chart,:on => :collection
    get :search,:on => :collection
    get :simple_search,:on => :collection
    put :reset,:on => :member
  end

  resources :computer_bills do
    get :search,:on => :collection
  end

  root :to => "dashboard#index"

end

app/models/distribution_list.rb
#coding: utf-8
class DistributionList < ActiveRecord::Base
  belongs_to :user
  has_many :carrying_bills
  belongs_to :org
  validates_presence_of :org_id,:bill_date
  #定义状态机
  state_machine :initial => :billed do
    after_transition do |distribution_list,transition|
      distribution_list.carrying_bills.each {|bill| bill.standard_process}
    end
    event :process do
      transition :billed =>:distributed
    end
  end

  default_value_for :bill_date,Date.today
  #导出到csv
  def to_csv
    ret = ["分货日期:",self.bill_date,"机构:",self.org.name].export_line_csv(true)
    csv_carrying_bills = CarryingBill.to_csv(self.carrying_bills.search,LoadList.carrying_bill_export_options,false)
    ret + csv_carrying_bills
  end
  private
  def self.carrying_bill_export_options
    {
        :only => [],
        :methods => [
          :bill_date,:bill_no,:goods_no,:from_customer_name,:from_customer_phone,:from_customer_mobile,
          :to_customer_name,:to_customer_phone,:to_customer_mobile,
          :pay_type_des,
          :carrying_fee,:goods_fee,
          :note,:human_state_name
      ]}
  end
end

app/controllers/distribution_lists_controller.rb
#coding: utf-8
class DistributionListsController < BaseController
  include BillOperate
  #GET search
  #显示查询窗口
  def search
    render :partial => "search"
  end
  def show
    super do |format|
      format.csv {send_data resource.to_csv}
    end
  end
end

app/helpers/distribution_lists_helper.rb
#coding: utf-8
#coding: utf-8
module DistributionListsHelper
end

app/views/distribution_lists/_extra_toolbar.html.erb
<%if params[:action] == "show"%>
  <li>
    <%= link_to image_tag("document-excel-table.png",:alt => "导出为EXCEL"), resource_path(resource,:format => :csv),:title => "导出为EXCEL",:class => "tipsy"  %>
  </li>
<%end%>

app/views/distribution_lists/_form.html.erb
<%= semantic_form_for resource ,:remote => true,:html => {:id => "distribution_list_form",:class => "bill_selector"} do |f|%>
  <%= f.inputs do %>
    <%= f.hidden_field :user_id,:value => current_user.id if f.object.new_record?%>
    <%= f.input :bill_date,:as => :string,:input_html =>{:readonly => true,:size => 20,:class => 'datepicker'} %>
    <%= f.input :org_id,:label => "到货地",:as => :select,:collection => current_ability_orgs_for_select,:include_blank => false,:input_html => {:class => "select_org",:id => "to_org_id"} %>
    <%=hidden_field_tag :state_eq,:reached%>
    <%=hidden_field_tag :type_in,"","data-type" => ['ComputerBill','HandBill','ReturnBill'].to_json %>
  <% end %>
<% end%>

app/views/distribution_lists/_form_after.html.erb
<hr/>
<div class='actions-bar text-right'>
  <%= link_to image_tag("plus-white.png") + "选择要分货的运单", search_carrying_bills_path(:hide_fields => '.carrying_fee,.insured_fee',:show_fields => '.carrying_fee_th'),:class => 'fancybox tipsy sexybutton sexysimple sexyblue',:title => "录入查询条件,查询要分货的运单" %>
</div>
<hr/>
<div id="table_wrap"></div>

app/views/distribution_lists/_search.html.erb
<%= semantic_form_for resource_class.search,:html => {:method => :get,:style => "width : 300px;" } do |f|%>
  <%= hidden_field_tag :direction,params[:direction] %>
  <%= hidden_field_tag :sort,params[:sort] %>
  <%= f.inputs do %>
    <%= f.input :bill_date_gte,:label => "分货日期",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
    <%= f.input :bill_date_lte,:label => "~",:as => :string,:input_html =>{:class => 'datepicker',:size => 20,:readonly => true,:value => Date.today} %>
    <%= f.input :org_id_eq,:label => "分理处",:as => :select,:collection => current_ability_orgs_for_select,:input_html => {:class => "select_org"} %>
  <% end %>
  <%=f.buttons do %>
    <%=submit_tag "查询分货清单",:class => "sexybutton sexysimple sexyblue" %>
  <% end %>
<% end%>

app/views/distribution_lists/_show.html.erb
<table class='table' data-detailUrl='<%=distribution_list_carrying_bills_path(resource)%>'>
  <tr>
    <td>日期:</td>
    <td><%=resource.bill_date.strftime('%Y-%m-%d')%></td>
    <td>分理处/分公司:</td>
    <td><%=resource.org.name%></td>
    <td>状态:</td>
    <td><%=resource.human_state_name%></td>
    <td>操作员:</td>
    <td><%=resource.user%></td>
  </tr>
</table>
<div id="table_wrap"></div>